const data = {
    products:[
        {
            _id:'1',
            name:'Nike Slim Shirt',
            category: 'Shirts',
            image: '/images/p1.jpg',
            price: 120,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'2',
            name:'Adidas Slim Shirt',
            category: 'Shirts',
            image: '/images/p2.jpg',
            price: 111,
            brand: 'Adidas',
            rating: 3.5,
            numReviews: 7,
            description: 'high quality product',
        },
        {
            _id:'3',
            name:'Polo Slim Shirt',
            category: 'Shirts',
            image: '/images/p3.jpg',
            price: 220,
            brand: 'Polo',
            rating: 5,
            numReviews: 12,
            description: 'high quality product',
        },
        {
            _id:'4',
            name:'Nike Slim Pant',
            category: 'Pants',
            image: '/images/p4.jpg',
            price: 50,
            brand: 'Nike',
            rating: 4.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id:'5',
            name:'Adidas Slim Pants',
            category: 'Shirts',
            image: '/images/p5.jpg',
            price: 120,
            brand: 'Adidas',
            rating: 5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id:'6',
            name:'Lacoste Slim Pant',
            category: 'Pants',
            image: '/images/p6.jpg',
            price: 90,
            brand: 'Lacoste',
            rating: 3.5,
            numReviews: 15,
            description: 'high quality product',
        },
    ]
}
export default data;